/* WAV-PRG: a program for converting C64 tapes into files suitable
 * for emulators and back.
 *
 * Copyright (c) Fabrizio Gennari, 1998-2003
 *
 * The program is distributed under the GNU General Public License.
 * See file LICENSE.TXT for details.
 *
 * tapfile_write.c : writes data generated by prg->wav part to TAP file
 *
 * This file belongs to the prg->wav part
 * This file is part of WAV-PRG core processing files
 */

#include <stdio.h>
#include <errno.h>
#include <sys/types.h>
#include <stdlib.h>
#include <string.h>
#include "tapfile_write.h"

enum wav2prg_bool tapfile_write_set_pulse(struct tap_handle *handle, u_int32_t ncycles){
  unsigned char byte, threebytes[3];

  if (ncycles < 256 * 8) {
    byte = ncycles / 8;
    if (fwrite(&byte, 1, 1, handle->file) != 1) {
      return wav2prg_false;
    }
    return wav2prg_true;
  }
  byte = 0;
  if (fwrite(&byte, 1, 1, handle->file) != 1)
    return wav2prg_false;
  if (handle->version == 0)
    return 0;
  threebytes[0] = ncycles & 0xFF;
  threebytes[1] = (ncycles >> 8) & 0xFF;
  threebytes[2] = (ncycles >> 16) & 0xFF;
  if (fwrite(threebytes, 3, 1, handle->file) != 1)
    return wav2prg_false;
  return wav2prg_true;
}

void tapfile_write_close(struct tap_handle *handle){
  long size;
  unsigned char size_header[4];

  do{
    if ((fseek(handle->file, 0, SEEK_END)) != 0)
      break;
    if ((size = ftell(handle->file)) == -1)
      break;
    size -= 20;
    if (size < 0)
      break;
    size_header[0] = (unsigned char) (size & 0xFF);
    size_header[1] = (unsigned char) ((size >> 8) & 0xFF);
    size_header[2] = (unsigned char) ((size >> 16) & 0xFF);
    size_header[3] = (unsigned char) ((size >> 24) & 0xFF);
    if ((fseek(handle->file, 16, SEEK_SET)) != 0)
      break;
    fwrite(size_header, 4, 1, handle->file);
  }while(0);
  fclose(handle->file);
  free(handle);
};

enum wav2prg_bool tapfile_init_write(char *name, struct tap_handle **file, unsigned char version, unsigned char machine){
  char c64_tap_header[] = "C64-TAPE-RAW\0\0\0\0\0\0\0\0";
  char c16_tap_header[] = "C16-TAPE-RAW\0\2\0\0\0\0\0\0";
  char *tap_header = (machine == 0 ? c64_tap_header : c16_tap_header);
  FILE *outfile;
  struct tap_handle *handle;

  if (version != 0 && version != 1) {
    return wav2prg_false;
  }
  outfile = fopen(name, "wb");
  if (outfile == NULL) {
    return wav2prg_false;
  }
  tap_header[12] = version;

  if (fwrite(tap_header, 20, 1, outfile) != 1) {
    fclose(outfile);
    return wav2prg_false;
  }
  handle = malloc(sizeof(struct tap_handle));
  if (handle == NULL) {
    fclose(outfile);
    return wav2prg_false;
  }
  handle->file = outfile;
  handle->version = version;

  *file = handle;
  return wav2prg_true;
}

