#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDD_ABOUT                       101
#define IDD_STATUS                      102
#define IDD_T64_NAME                    103
#define IDD_WAV2PRG                     104
#define IDD_ADVANCED                    108
#define IDC_FILE_PROGRESS               1000
#define IDC_ENTRY_PROGRESS              1001
#define IDC_FILE_TEXT                   1002
#define IDC_ENTRY_TEXT                  1003
#define IDC_FOUND                       1004
#define IDC_T64_NAME                    1005
#define IDC_PLUGIN_DIR                  1006
#define IDC_PLUGINS                     1007
#define IDC_CONVERSION_DIR              1008
#define IDC_BROKEN                      1009
#define IDC_FROM_FILE                   1010
#define IDC_FROM_SOUND                  1011
#define IDC_TO_PRG                      1012
#define IDC_TO_P00                      1013
#define IDC_TO_T64                      1014
#define IDC_DO_NOT_SAVE                 1015
#define IDC_TO_TAP                      1016
#define IDC_INVERTED                    1017
#define IDC_MIN_HEIGHT                  1018
#define IDC_FREQ                        1019
#define IDC_CLOCK                       1020
#define IDC_CHANGE_PLUGIN_DIR           1021
#define IDC_ADVANCED_OPTIONS            1022
#define IDC_CHANGE_CONVERSION_DIR       1023
#define IDC_TAPENCODER_STATUS           1024
#define IDC_TAPDECODER_STATUS           1025
#define IDC_PABLIO_STATUS               1026
#define IDC_AUDIOFILE_STATUS            1027
#define IDC_LIMITED_INCREMENT           1028
#define IDC_LIMITED_DIST_FROM_AVG       1029
#define IDC_DISTANCE                    1030
#define IDC_CHANGE_DISTANCE             1033
